name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Changelog
        run: |
          node ./bin/get-changelog.js "$(git log $(git tag --sort=committerdate | tail -1)..HEAD --oneline --pretty=format:"%an%x09%s")"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG
          path: changelogs/CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'release.tar.gz'
          bodyFile: 'changelogs/CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
