name: Update Version
on:
  push:
    branches:
      - main # Change this to your default branch
jobs:
  update-version:
    name: update-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install dependencies (please, check you dependencies)
        run: npm ci

      - name: Linter (please, run `npm run lint` locally before merge)
        run: |
          npm run lint:ci

      - name: Tests (please, run `npm run test` locally before merge)
        run: |
          npm run test:ci

      - name: Build
        run: npm run build
